### ISSUE TITLE
Details endpoint does not support external dependencies with hyphen

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#25]
The following URL does not display the information properly:

https://infinite-harbor-38537.herokuapp.com/details?info=alvarocavalcanti/my-dev-templates#1:open

Instead of:

```javascript
{
    "dependencies": [
        "alvarocavalcanti/my",
        "dev",
        "templates"
    ]
}
```

It should display:
```javascript
{
    "dependencies": [
        "alvarocavalcanti/my-dev-templates#1 is open"
    ]
}
```

**Comment by AshwinMathews** [comment]
```
def details():
    info = request.args.get('info')
    dependencies_and_states = info.split('-')
    dependencies_info = [dep.replace(':', ' is ') for dep in info]
```

Issue is caused by this line, can't find any information on "states" for pierre-decheck, can you clarify? Or point me in the right direction? (Sorry if this is really obvious, my first attempted contribution)

**Comment by shw1n** [comment]
Attempting to fix this, but unfortunately everything after and including the pound sign ('#') is not sent to the server, as the client handles it. 

So only "alvarocavalanti/my-dev-templates" is sent, which we can display by removing the state check if that's desired behavior, or by changing the url format (depending on where these URLs are generated)

**Comment by alvarocavalcanti** [comment]
@shw1n What do you mean by "the client handles it"? I mean, if I click on the URL above, the browser has it fully on the address bar:

<img width="826" alt="captura de tela 2018-06-21 as 16 29 00" src="https://user-images.githubusercontent.com/512234/41741013-426609e2-7570-11e8-8c95-4c1e9eabe77d.png">

So, I didn't understand what you meant. Can you clarify, please?

**Comment by Sando1** [comment]
Attempting to work on this, if still open

**Comment by alvarocavalcanti** [comment]
It's still open @Sando1, thanks!

**Comment by geekyprince** [comment]
Attempting to work on this, if still open??

**Comment by alvarocavalcanti** [comment]
It's still open @geekyprince, thanks for the interest!

**Comment by geekyprince** [comment]
@alvarocavalcanti  Can please clarify what "info" may consist of like any example with multiple dependencies

**Comment by alvarocavalcanti** [comment]
You can have a look on the line below where we generate the `info` param:
https://github.com/alvarocavalcanti/pierre-decheck/blob/8375f0e9bc49aaaa3bb43526cf57e88e84672a8c/lib/pierre.py#L274

**Comment by geekyprince** [comment]
@alvarocavalcanti Please review my pull request and suggest any further changes if required
