### ISSUE TITLE
Make a UI for the details endpoint

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#26]
Currently, the details endpoint displays raw JSON data. It should display that data in a more user-friendly manner.

There is no current requirement for technology to be used here, and for the data itself, it only needs to be the same that is currently provided.

**Comment by Nibba2018** [comment]
Hello @alvarocavalcanti , I would like to work on this issue.

**Comment by alvarocavalcanti** [comment]
Hey @Nibba2018 thanks for being interested, but unfortunately this project hasn't been active for a good while. Also, GitHub has introduced new ways of interactions that would be preferable than Pierre's architecture.

I will archive this repo now, but, again, thanks for checking it out!
