### ISSUE TITLE
Add a STATUS endpoint

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#30]
The status endpoint should display the data from the last received event

**Comment by mosheeshel** [comment]
Do you really want to add state to the service? Right now it's a very nice stateless application.
I don't see the value of this additional call

**Comment by alvarocavalcanti** [comment]
The idea here isn't to save the state of every PR that interacted with Pierre, but to display the status of Pierre itself.

It was your usage, @mosheeshel, that gave me this idea, like you said that the webhook was green, but Pierre didn't perform any checks. In this case I would store, in memory, the last payload received and some flag to indicate if it was successful processed or not.

I also understand that this is more of a `debug` feature than a `user story` feature, and thus this feature might not need to be developed.

**Comment by alvarocavalcanti** [comment]
I don't think this is needed anymore. After adding more logging calls, like in 4d0cd2bdb0aff1654a4e44fb09fe2c7c819c7115 I feel the needs to for this have been satisfied.
