### ISSUE TITLE
Does not work for new comment added anymore

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#34]
After the payload updated, new comments to PR do not get their dependencies found

**Comment by mosheeshel** [comment]
might have been resolved by my fix [here](https://github.com/alvarocavalcanti/pierre-decheck/pull/35/files#diff-d355af669766ee3562643e8e5034f715R80)
not sure about the scenario behind this

**Comment by alvarocavalcanti** [comment]
It is fixed indeed. I've just checked.

**Comment by alvarocavalcanti** [comment]
fixed by #35
