### ISSUE TITLE
Perform a check when the details or a comment is updated

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#46]

**Comment by kamal** [comment]
Does this fall under the same issue where a check is not performed when a dependent PR is merged?

**Comment by alvarocavalcanti** [comment]
I don't think so @kamal 

This one is depends merely on responding to a couple new events, on the current PR. While #29 involves some new infrastructure to observe and generate events for external changes.

**Comment by mosheeshel** [comment]
Exactly, this one requires just scaning events from the same PR, #29 requires that we scan for events in all PRs in all Repositories "connected" to this PR

**Comment by alvarocavalcanti** [comment]
Yes! And the main point of #29 is that it brings the need of data persistence, which *Pierre* does not have at the moment.

**Comment by mosheeshel** [comment]
Exactly 😟

**Comment by mosheeshel** [comment]
Could be developed as an optional module, supporting a simple key/value protocol 

These offer a single API for multiple backends...
https://pypi.org/project/dogpile.cache/
https://pypi.org/project/HermesCache/

Could also include configuration of what repos to scan for cold start situation (disaster recovery or migration)

Could be a really neat feature, not enough hours in a day 😯

**Comment by pomu0325** [comment]
Current implementation seems to do `perform a check when the details or a comment is updated`, because editing PR description or comments also triggers a webhook.

But I found a bug related to this issue so I filed a new one: #75
