### ISSUE TITLE
Add integration tests for GitHub payloads

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#60]
We need to be aware when GitHub changes the payloads that we expect.

**Comment by masihtamsoy** [comment]
Hi, @alvarocavalcanti want to check this out. Can you provide me initial pointers to start.

**Comment by alvarocavalcanti** [comment]
Sure @masihtamsoy, here it goes.

We already have a unit test suite, now we need an integration one to make sure we're checking for any change in the payloads we use from GitHub.

We should go over the code and identify all the requests to GitHub and their associated data fetching, for instance:

https://github.com/alvarocavalcanti/pierre-decheck/blob/0925d647e3ca18d2cf3d336caa43cf66c963c24b/lib/pierre.py#L209

On this line we are relying on the `labels` field to exist and for it to have a `name` field itself. And this was modified recently, as the first implementation used `description` instead of `name`. And this information is retrieved at this line:

https://github.com/alvarocavalcanti/pierre-decheck/blob/0925d647e3ca18d2cf3d336caa43cf66c963c24b/lib/pierre.py#L225

Once we have all the tests written, we need to modify the circle-ci [config file](https://github.com/alvarocavalcanti/pierre-decheck/blob/99e48bccc50d48f8be5dd476b1dfe174e997e8dd/.circleci/config.yml#L2) to run them once per day and be detached from the continuous integration cycle.

**Comment by alvarocavalcanti** [comment]
Check out this page on how to configure scheduled jobs:

https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

**Comment by masihtamsoy** [comment]
Thanks @alvarocavalcanti

**Comment by arudzinska** [comment]
Hi, @masihtamsoy, are you still working on this issue?
