### ISSUE TITLE
Convert pierre-decheck into a GitHub Action

### ISSUE THREAD

**Issue by serucee** [alvarocavalcanti/pierre-decheck#69]
Is there any plan to provide this as a GitHub Action?
The question is somehow related to https://github.com/alvarocavalcanti/pierre-decheck/issues/62
It shouldn't be too much effort since a Dockerfile already exists

Benefits:
* No self hosting required
* Easy to setup/configure
* No Auth troubles (github provides a specific token for GitHub actions)
* Fully managed in the GitHub context

**Comment by alvarocavalcanti** [comment]
There are no plans at the moment, but I can surely look into the matter. Specially based on the benefits listed above.

At the same time, would you be interested/available in contributing with this feature?

**Comment by serucee** [comment]
Hi, i see.
I actually started looking into it today and made a rough prototype using only bash and having a smaller featureset.

I think it would be quite easy to move it to an action, so yes i could contribute.

**Comment by alvarocavalcanti** [comment]
Great! It would be great to collaborate with you on that
