### ISSUE TITLE
Dependency created through review comment is ignored by later comments

### ISSUE THREAD

**Issue by pomu0325** [alvarocavalcanti/pierre-decheck#75]
## Steps to reproduce

- Write review comments with dependency description like `depends on #xx`
  - Then check fails: 
<img src=https://user-images.githubusercontent.com/216323/85876998-77acf580-b811-11ea-95bc-29e165c590ce.png width=50%>

- Write PR comments without dependency description.
  - 💥 Then dependency is cleared unexpectedly:
<img src=https://user-images.githubusercontent.com/216323/85877285-df634080-b811-11ea-8854-330566a5bfa8.png width=50%>

## Cause

Dependencies are checked only through event payload and comments here:

https://github.com/alvarocavalcanti/pierre-decheck/blob/7f8efcd366efa9f30a583474c6bc4f71df6b02ac/lib/pierre.py#L97-L99

**Comment by alvarocavalcanti** [comment]
Good catch! Thanks for raising it!

**Comment by pomu0325** [comment]
I think this issue can be resolved by fetching `bodies` for all events(including review comments)  with `Timeline` api (as used in #76).
I'm already working on this in my forked repo :)
